### ISSUE TITLE
Android use react-native run-android package success

### ISSUE THREAD

**Issue by wuweiit** [damly/react-native-vunun-live#1]
Android use react-native run-android package success。
android simulator runtime exception：

 Caused by: java.lang.UnsatisfiedLinkError: Couldn't load yuv: findLibrary returned null
E/AndroidRuntime( 3655):        at java.lang.Runtime.loadLibrary(Runtime.java:365)
E/AndroidRuntime( 3655):        at java.lang.System.loadLibrary(System.java:535)
E/AndroidRuntime( 3655):        at net.ossrs.yasea.SrsEncoder.<clinit>(SrsEncoder.java:558)

thank for you Solve the problem.

**Comment by damly** [comment]
你是在模拟器里面运行的吗？
我没有在模拟器里面测试过，请用手机测试一下

**Comment by wuweiit** [comment]
原来都是中国人，我还以为是外国人的，哈哈。
我用的iphone，刚买了一个小米3s做测试，今天到货。回家可以再测。

你写的这套直播组件很实用，还有你的录音组件。都不错！
